In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv('movies.csv')
credits = pd.read_csv('credits.csv')

In [3]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [4]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [5]:
movies.shape

(4803, 20)

In [6]:
credits.shape

(4803, 4)

In [7]:
movies = movies.merge(credits, on='title')

In [8]:
movies.shape

(4809, 23)

In [9]:
movies.isnull().sum()

budget                     0
genres                     0
homepage                3096
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
movie_id                   0
cast                       0
crew                       0
dtype: int64

In [10]:
# What features required to build recomandation system

In [11]:
# genere, keywords, overview, title, cast, crew, movie_id 
# all other drop

In [12]:
movies.original_language.value_counts()

original_language
en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ro       2
id       2
ar       2
vi       1
sl       1
ps       1
no       1
ky       1
hu       1
pl       1
af       1
nb       1
tr       1
is       1
xx       1
te       1
el       1
Name: count, dtype: int64

In [13]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [14]:
movies = movies[['genres', 'keywords', 'overview','title', 'cast', 'crew', 'movie_id']]

In [15]:
movies.head()

,genres,keywords,overview,title,cast,crew,movie_id
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",19995
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",285
2,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",206647
3,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",49026
4,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",49529

In [16]:
# genere, cast, crew and keyword written in json

In [17]:
import ast

In [18]:
# Abstract syntax tree

In [19]:
def convert(text):
    l = []
    for i in ast.literal_eval(text):
        l.append(i['name'])
    return l

In [20]:
movies['genres'] = movies['genres'].apply(convert)

In [21]:
movies.head()

,genres,keywords,overview,title,cast,crew,movie_id
0,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",19995
1,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",285
2,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",A cryptic message from Bond’s past sends him o...,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",206647
3,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",49026
4,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","John Carter is a war-weary, former military ca...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",49529

In [22]:
movies['keywords'] = movies['keywords'].apply(convert)

In [23]:
movies.head()

,genres,keywords,overview,title,cast,crew,movie_id
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",19995
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",285
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",206647
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",49026
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",49529

In [24]:
def convert_cast(text):
    l = []
    counter = 0
    for i in ast.literal_eval(text):
        if counter==3:
            break
        l.append(i['name'])
        counter+=1
    return l

In [25]:
movies['cast'] = movies['cast'].apply(convert_cast)

In [26]:
movies.head()

,genres,keywords,overview,title,cast,crew,movie_id
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de...",19995
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de...",285
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de...",206647
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de...",49026
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de...",49529

In [27]:
def convert_director(text):
    l = []
    for i in ast.literal_eval(text):
        if i['job'] == 'Director':
            l.append(i['name'])
    return l

In [28]:
movies['crew'] = movies['crew'].apply(convert_director)

In [29]:
movies.head()

,genres,keywords,overview,title,cast,crew,movie_id
0,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],19995
1,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],285
2,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",A cryptic message from Bond’s past sends him o...,Spectre,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],206647
3,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],49026
4,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","John Carter is a war-weary, former military ca...",John Carter,"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],49529

In [30]:
def collapse(l):
    l1 = []
    for i in l:
        l1.append(i.replace(' ', ''))
    return l1

In [31]:
# remove space between wordas

In [32]:
movies['cast'] = movies['cast'].apply(collapse)
movies['crew'] = movies['crew'].apply(collapse)
movies['genres'] = movies['genres'].apply(collapse)
movies['keywords'] = movies['keywords'].apply(collapse)

In [33]:
movies.head()

,genres,keywords,overview,title,cast,crew,movie_id
0,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],19995
1,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],285
2,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",A cryptic message from Bond’s past sends him o...,Spectre,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],206647
3,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],49026
4,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","John Carter is a war-weary, former military ca...",John Carter,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],49529

In [34]:
# Tokenization for words for overview

In [35]:
movies.isnull().sum()

genres      0
keywords    0
overview    3
title       0
cast        0
crew        0
movie_id    0
dtype: int64

In [36]:
movies.dropna(inplace=True)

In [37]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [38]:
movies.head()

,genres,keywords,overview,title,cast,crew,movie_id
0,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],19995
1,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],285
2,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...",Spectre,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],206647
3,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],49026
4,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],49529

In [39]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [40]:
movies.head()

,genres,keywords,overview,title,cast,crew,movie_id,tags
0,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],19995,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],285,"[Captain, Barbossa,, long, believed, to, be, d..."
2,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bond’s, past, send...",Spectre,"[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],206647,"[A, cryptic, message, from, Bond’s, past, send..."
3,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney...",The Dark Knight Rises,"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],49026,"[Following, the, death, of, District, Attorney..."
4,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili...",John Carter,"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],49529,"[John, Carter, is, a, war-weary,, former, mili..."

In [41]:
new = movies.drop(columns=['overview', 'genres', 'keywords', 'cast', 'crew'])

In [42]:
new.head()

,title,movie_id,tags
0,Avatar,19995,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,Pirates of the Caribbean: At World's End,285,"[Captain, Barbossa,, long, believed, to, be, d..."
2,Spectre,206647,"[A, cryptic, message, from, Bond’s, past, send..."
3,The Dark Knight Rises,49026,"[Following, the, death, of, District, Attorney..."
4,John Carter,49529,"[John, Carter, is, a, war-weary,, former, mili..."

In [43]:
new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4806 entries, 0 to 4808
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     4806 non-null   object
 1   movie_id  4806 non-null   int64
 2   tags      4806 non-null   object
dtypes: int64(1), object(2)
memory usage: 150.2+ KB

In [44]:
new['tags'] = new['tags'].apply(lambda x: " ".join(x))

In [45]:
new.head()

,title,movie_id,tags
0,Avatar,19995,"In the 22nd century, a paraplegic Marine is di..."
1,Pirates of the Caribbean: At World's End,285,"Captain Barbossa, long believed to be dead, ha..."
2,Spectre,206647,A cryptic message from Bond’s past sends him o...
3,The Dark Knight Rises,49026,Following the death of District Attorney Harve...
4,John Carter,49529,"John Carter is a war-weary, former military ca..."

In [46]:
new.to_csv("new_dataset.csv")

In [47]:
# collabarative filtre based recomandation system

In [48]:
# nlp  concept- bag of words use on tags

In [49]:
# we can do lematization before vectorization

In [50]:
# we can also use tfidf instead of count vectorizer

In [51]:
from sklearn.feature_extraction.text import CountVectorizer

In [52]:
cv = CountVectorizer(stop_words='english',max_features=5000, binary=True)

In [92]:
vector = cv.fit_transform(new['tags'])

In [93]:
vector.shape

(4806, 5000)

In [76]:
cv = CountVectorizer(stop_words='english',max_features=5000, binary=True)

In [77]:
vector = cv.fit(new['tags'])

In [54]:
vector.shape

(4806, 5000)

In [71]:
type(new['tags'])

pandas.core.series.Series

In [70]:
import pickle

In [84]:
pickle.dump(vector, open("vector_file1", "wb"))

In [83]:
vector

<4806x5000 sparse matrix of type '<class 'numpy.int64'>'
	with 134300 stored elements in Compressed Sparse Row format>

In [55]:
# cosine similarity - angle between 2 vecctors
# cosine similarity range is from 0 deg to 180 deg
# closer to 0 deg similar movies
# closer to 180 deg not similar movies
# dot product of 2 vectors divided by l2 norm

In [56]:
from sklearn.metrics.pairwise import cosine_similarity

In [85]:
similarity = cosine_similarity(vector)

In [86]:
cosine_similarity(vector)[0]

array([1.        , 0.09837388, 0.06780635, ..., 0.02886751, 0.03279129,
       0.        ])

In [59]:
# 1 means 1st movie vs 1st moviea
cosine_similarity(vector)[0].shape

(4806,)

In [91]:
print(len(similarity[0]))

4806

In [60]:
similarity.shape

(4806, 4806)

In [61]:
new.head(1)

    title  movie_id                                               tags
0  Avatar     19995  In the 22nd century, a paraplegic Marine is di...

In [62]:
new[new['title'] == 'The Dark Knight Rises']

,title,movie_id,tags
3,The Dark Knight Rises,49026,Following the death of District Attorney Harve...

In [63]:
new[new['title'] == 'The Dark Knight Rises'].index[0]

3

In [89]:
similarity[3]

array([0.05216405, 0.0256579 , 0.05305581, ..., 0.06776309, 0.0513158 ,
       0.07958372])

In [64]:
similarity[new[new['title'] == 'The Dark Knight Rises'].index[0]]

array([0.05216405, 0.0256579 , 0.05305581, ..., 0.06776309, 0.0513158 ,
       0.07958372])

In [65]:
print(enumerate(similarity[new[new['title'] == 'The Dark Knight Rises'].index[0]]))

<enumerate object at 0x00000272CD29D4E0>

In [87]:
list(enumerate(similarity[new[new['title'] == 'The Dark Knight Rises'].index[0]]))

[(0, 0.0521640530957301),
 (1, 0.025657900289539272),
 (2, 0.0530558109077291),
 (3, 1.0000000000000007),
 (4, 0.047619047619047616),
 (5, 0.06776309271789384),
 (6, 0.06388765649999399),
 (7, 0.06862635163075162),
 (8, 0.02749286996141075),
 (9, 0.1853959098637286),
 (10, 0.07460470969529907),
 (11, 0.07142857142857142),
 (12, 0.029160592175990218),
 (13, 0.02608202654786505),
 (14, 0.07460470969529907),
 (15, 0.022875450543583874),
 (16, 0.06952346619889824),
 (17, 0.02231053741265801),
 (18, 0.044086671417740544),
 (19, 0.04973647313019938),
 (20, 0.057788559639706465),
 (21, 0.08247860988423225),
 (22, 0.0),
 (23, 0.0),
 (24, 0.09799919151000504),
 (25, 0.12244897959183672),
 (26, 0.09523809523809523),
 (27, 0.042591770999996),
 (28, 0.0893633203101749),
 (29, 0.12244897959183672),
 (30, 0.0871420401900598),
 (31, 0.0893633203101749),
 (32, 0.021295885499998),
 (33, 0.058321184351980436),
 (34, 0.0),
 (35, 0.062347968638854966),
 (36, 0.09658905768325902),
 (37, 0.0),
 (38, 0.06460957383809221),
 (39, 0.07824607964359515),
 (40, 0.02749286996141075),
 (41, 0.14285714285714285),
 (42, 0.02699746235780194),
 (43, 0.07142857142857142),
 (44, 0.038180177416060626),
 (45, 0.08817334283548109),
 (46, 0.02486823656509969),
 (47, 0.07924288517503274),
 (48, 0.0215365246126974),
 (49, 0.028016590734026292),
 (50, 0.0893633203101749),
 (51, 0.05727026612409094),
 (52, 0.04899959575500252),
 (53, 0.04697113923010208),
 (54, 0.0),
 (55, 0.021295885499998),
 (56, 0.12182898077463451),
 (57, 0.05714285714285714),
 (58, 0.09799919151000504),
 (59, 0.0416757118565413),
 (60, 0.07576144084141578),
 (61, 0.029787773436724965),
 (62, 0.038180177416060626),
 (63, 0.0),
 (64, 0.031943828249996996),
 (65, 0.3711537444790452),
 (66, 0.02857142857142857),
 (67, 0.025657900289539272),
 (68, 0.05714285714285714),
 (69, 0.01875806183710322),
 (70, 0.02652790545386455),
 (71, 0.025253813613805264),
 (72, 0.11206636293610517),
 (73, 0.031173984319427483),
 (74, 0.02699746235780194),
 (75, 0.02749286996141075),
 (76, 0.08817334283548109),
 (77, 0.061858957413174195),
 (78, 0.02608202654786505),
 (79, 0.07142857142857142),
 (80, 0.07045670884515312),
 (81, 0.017998308238534627),
 (82, 0.12434118282549846),
 (83, 0.025253813613805264),
 (84, 0.06862635163075162),
 (85, 0.09145491423778283),
 (86, 0.02652790545386455),
 (87, 0.02699746235780194),
 (88, 0.02749286996141075),
 (89, 0.02040816326530612),
 (90, 0.0),
 (91, 0.0530558109077291),
 (92, 0.024147264420814756),
 (93, 0.09394227846020416),
 (94, 0.05957554687344993),
 (95, 0.06535653014254486),
 (96, 0.07576144084141578),
 (97, 0.11587244366483038),
 (98, 0.02608202654786505),
 (99, 0.07824607964359515),
 (100, 0.060914490387317256),
 (101, 0.07460470969529907),
 (102, 0.0435710200950299),
 (103, 0.061858957413174195),
 (104, 0.07697370086861782),
 (105, 0.03571428571428571),
 (106, 0.0),
 (107, 0.0430730492253948),
 (108, 0.09269795493186431),
 (109, 0.0),
 (110, 0.0),
 (111, 0.02749286996141075),
 (112, 0.0549857399228215),
 (113, 0.022875450543583874),
 (114, 0.0),
 (115, 0.07142857142857142),
 (116, 0.14920941939059815),
 (117, 0.0),
 (118, 0.0),
 (119, 0.3370101854969078),
 (120, 0.05050762722761053),
 (121, 0.05714285714285714),
 (122, 0.11664236870396087),
 (123, 0.061224489795918366),
 (124, 0.0),
 (125, 0.05050762722761054),
 (126, 0.07349939363250378),
 (127, 0.058868813120866725),
 (128, 0.0521640530957301),
 (129, 0.04575090108716775),
 (130, 0.05714285714285714),
 (131, 0.02608202654786505),
 (132, 0.025253813613805264),
 (133, 0.0),
 (134, 0.060914490387317256),
 (135, 0.05714285714285714),
 (136, 0.04973647313019938),
 (137, 0.03962144258751637),
 (138, 0.025253813613805264),
 (139, 0.10309826235529033),
 (140, 0.06693161223797403),
 (141, 0.0),
 (142, 0.0),
 (143, 0.021295885499998),
 (144, 0.025253813613805264),
 (145, 0.0416757118565413),
 (146, 0.022875450543583874),
 (147, 0.08247860988423225),
 (148, 0.06388765649999399),
 (149, 0.0430730492253948),
 (150, 0.08001600480160055),
 (151, 0.033671751485073696),
 (152, 0.02749286996141075),
 (153, 0.1237179148263484),
 (154, 0.029787773436724965),
 (155, 0.02258769757263128),
 (156, 0.06251356778481196),
 (157, 0.12777531299998798),
 (158, 0.02231053741265801),
 (159, 0.060914490387317256),
 (160, 0.11664236870396087),
 (161, 0.0),
 (162, 0.033671751485073696),
 (163, 0.0915018021743355),
 (164, 0.08099238707340582),
 (165, 0.06460957383809221),
 (166, 0.10101525445522105),
 (167, 0.060914490387317256),
 (168, 0.07244179326244427),
 (169, 0.0861460984507896),
 (170, 0.1224989893875063),
 (171, 0.02608202654786505),
 (172, 0.07636035483212125),
 (173, 0.02652790545386455),
 (174, 0.08099238707340582),
 (175, 0.0),
 (176, 0.0549857399228215),
 (177, 0.0),
 (178, 0.02857142857142857),
 (179, 0.031943828249996996),
 (180, 0.10418927964135324),
 (181, 0.0),
 (182, 0.0915018021743355),
 (183, 0.03962144258751637),
 (184, 0.022875450543583874),
 (185, 0.04899959575500252),
 (186, 0.061224489795918366),
 (187, 0.02749286996141075),
 (188, 0.08001600480160055),
 (189, 0.10394383930128556),
 (190, 0.021295885499998),
 (191, 0.024147264420814756),
 (192, 0.07244179326244427),
 (193, 0.061858957413174195),
 (194, 0.03962144258751637),
 (195, 0.029160592175990218),
 (196, 0.09947294626039876),
 (197, 0.0),
 (198, 0.1061116218154582),
 (199, 0.024147264420814756),
 (200, 0.033671751485073696),
 (201, 0.029160592175990218),
 (202, 0.0),
 (203, 0.07824607964359515),
 (204, 0.09523809523809523),
 (205, 0.10714285714285714),
 (206, 0.02348556961505104),
 (207, 0.02608202654786505),
 (208, 0.03571428571428571),
 (209, 0.15971914124998499),
 (210, 0.2414726442081475),
 (211, 0.0),
 (212, 0.1224989893875063),
 (213, 0.06460957383809221),
 (214, 0.029787773436724965),
 (215, 0.10647942749999),
 (216, 0.06734350297014739),
 (217, 0.09394227846020416),
 (218, 0.07142857142857142),
 (219, 0.056033181468052584),
 (220, 0.0),
 (221, 0.0),
 (222, 0.06388765649999399),
 (223, 0.046348977465932154),
 (224, 0.12244897959183672),
 (225, 0.07697370086861782),
 (226, 0.02652790545386455),
 (227, 0.02608202654786505),
 (228, 0.04575090108716775),
 (229, 0.0833514237130826),
 (230, 0.06001200360120042),
 (231, 0.0),
 (232, 0.05399492471560388),
 (233, 0.029787773436724965),
 (234, 0.023809523809523808),
 (235, 0.0),
 (236, 0.09137173558097589),
 (237, 0.058321184351980436),
 (238, 0.14285714285714285),
 (239, 0.042591770999996),
 (240, 0.04697113923010208),
 (241, 0.0521640530957301),
 (242, 0.1061116218154582),
 (243, 0.025253813613805264),
 (244, 0.09583148474999098),
 (245, 0.051315800579078544),
 (246, 0.08924214965063204),
 (247, 0.05957554687344993),
 (248, 0.11021667854435135),
 (249, 0.030457245193658628),
 (250, 0.029160592175990218),
 (251, 0.0),
 (252, 0.08247860988423227),
 (253, 0.042591770999996),
 (254, 0.0),
 (255, 0.02608202654786505),
 (256, 0.03464794643376185),
 (257, 0.056033181468052584),
 (258, 0.02106313659355673),
 (259, 0.12182898077463451),
 (260, 0.029160592175990218),
 (261, 0.04462107482531602),
 (262, 0.06613000712661082),
 (263, 0.031173984319427483),
 (264, 0.047619047619047616),
 (265, 0.0),
 (266, 0.07697370086861782),
 (267, 0.09352195295828244),
 (268, 0.0),
 (269, 0.0),
 (270, 0.023809523809523808),
 (271, 0.05050762722761053),
 (272, 0.062347968638854966),
 (273, 0.06388765649999399),
 (274, 0.05315774339537506),
 (275, 0.109971479845643),
 (276, 0.028016590734026292),
 (277, 0.07460470969529907),
 (278, 0.04697113923010208),
 (279, 0.1061116218154582),
 (280, 0.1043281061914602),
 (281, 0.10892755023757475),
 (282, 0.1061116218154582),
 (283, 0.1349873117890097),
 (284, 0.0215365246126974),
 (285, 0.08425254637422692),
 (286, 0.107682623063487),
 (287, 0.02486823656509969),
 (288, 0.0549857399228215),
 (289, 0.02449979787750126),
 (290, 0.08571428571428572),
 (291, 0.051315800579078544),
 (292, 0.030457245193658628),
 (293, 0.0),
 (294, 0.0),
 (295, 0.08247860988423225),
 (296, 0.05676567244564473),
 (297, 0.07142857142857142),
 (298, 0.07958371636159366),
 (299, 0.29172998299578906),
 (300, 0.04973647313019938),
 (301, 0.040008002400800276),
 (302, 0.02749286996141075),
 (303, 0.13041013273932525),
 (304, 0.09379030918551609),
 (305, 0.0),
 (306, 0.0),
 (307, 0.10647942749999),
 (308, 0.09583148474999098),
 (309, 0.0),
 (310, 0.08859623899229176),
 (311, 0.051315800579078544),
 (312, 0.11742784807525519),
 (313, 0.0),
 (314, 0.1188643277625491),
 (315, 0.05714285714285714),
 (316, 0.09523809523809523),
 (317, 0.07142857142857142),
 (318, 0.0),
 (319, 0.029787773436724965),
 (320, 0.029787773436724965),
 (321, 0.03464794643376185),
 (322, 0.07349939363250378),
 (323, 0.028016590734026292),
 (324, 0.05399492471560388),
 (325, 0.033671751485073696),
 (326, 0.02652790545386455),
 (327, 0.02608202654786505),
 (328, 0.0),
 (329, 0.04697113923010208),
 (330, 0.02652790545386455),
 (331, 0.0),
 (332, 0.0530558109077291),
 (333, 0.08247860988423225),
 (334, 0.06776309271789384),
 (335, 0.07824607964359515),
 (336, 0.0),
 (337, 0.04575090108716775),
 (338, 0.0),
 (339, 0.1061116218154582),
 (340, 0.02699746235780194),
 (341, 0.028016590734026292),
 (342, 0.107682623063487),
 (343, 0.0),
 (344, 0.0530558109077291),
 (345, 0.0631894097806702),
 (346, 0.0521640530957301),
 (347, 0.0),
 (348, 0.028016590734026292),
 (349, 0.033671751485073696),
 (350, 0.06862635163075162),
 (351, 0.1061116218154582),
 (352, 0.0),
 (353, 0.024147264420814756),
 (354, 0.0915018021743355),
 (355, 0.09811468853477787),
 (356, 0.08404977220207888),
 (357, 0.09035079029052512),
 (358, 0.0),
 (359, 0.062347968638854966),
 (360, 0.042591770999996),
 (361, 0.0530558109077291),
 (362, 0.062347968638854966),
 (363, 0.02106313659355673),
 (364, 0.02608202654786505),
 (365, 0.02449979787750126),
 (366, 0.0530558109077291),
 (367, 0.05957554687344993),
 (368, 0.0),
 (369, 0.13746434980705374),
 (370, 0.1564921592871903),
 (371, 0.046348977465932154),
 (372, 0.07697370086861782),
 (373, 0.0),
 (374, 0.0),
 (375, 0.02486823656509969),
 (376, 0.10263160115815709),
 (377, 0.14285714285714285),
 (378, 0.06734350297014739),
 (379, 0.04081632653061224),
 (380, 0.028016590734026292),
 (381, 0.038180177416060626),
 (382, 0.04123930494211613),
 (383, 0.04697113923010208),
 (384, 0.029787773436724965),
 (385, 0.0),
 (386, 0.06535653014254486),
 (387, 0.07824607964359515),
 (388, 0.0521640530957301),
 (389, 0.08571428571428572),
 (390, 0.0),
 (391, 0.019622937706955574),
 (392, 0.056033181468052584),
 (393, 0.02699746235780194),
 (394, 0.04575090108716775),
 (395, 0.0),
 (396, 0.0871420401900598),
 (397, 0.05714285714285714),
 (398, 0.07824607964359515),
 (399, 0.0),
 (400, 0.08748177652797065),
 (401, 0.03688555567816587),
 (402, 0.07824607964359515),
 (403, 0.0521640530957301),
 (404, 0.05957554687344993),
 (405, 0.1349873117890097),
 (406, 0.02449979787750126),
 (407, 0.04517539514526256),
 (408, 0.15228622596829314),
 (409, 0.02857142857142857),
 (410, 0.023809523809523808),
 (411, 0.02749286996141075),
 (412, 0.04973647313019938),
 (413, 0.025657900289539272),
 (414, 0.029787773436724965),
 (415, 0.09460945407607455),
 (416, 0.02699746235780194),
 (417, 0.0),
 (418, 0.0),
 (419, 0.047619047619047616),
 (420, 0.02449979787750126),
 (421, 0.08817334283548109),
 (422, 0.03464794643376185),
 (423, 0.0),
 (424, 0.08081220356417686),
 (425, 0.11587244366483038),
 (426, 0.019810721293758184),
 (427, 0.0),
 (428, 0.2040816326530612),
 (429, 0.031173984319427483),
 (430, 0.023809523809523808),
 (431, 0.0),
 (432, 0.047619047619047616),
 (433, 0.08404977220207888),
 (434, 0.02699746235780194),
 (435, 0.033671751485073696),
 (436, 0.028016590734026292),
 (437, 0.10263160115815709),
 (438, 0.025253813613805264),
 (439, 0.08247860988423225),
 (440, 0.04973647313019938),
 (441, 0.0),
 (442, 0.09269795493186431),
 (443, 0.0),
 (444, 0.08099238707340582),
 (445, 0.025253813613805264),
 (446, 0.06535653014254486),
 (447, 0.09394227846020416),
 (448, 0.04575090108716775),
 (449, 0.11428571428571428),
 (450, 0.02857142857142857),
 (451, 0.023174488732966077),
 (452, 0.031943828249996996),
 (453, 0.07697370086861782),
 (454, 0.046348977465932154),
 (455, 0.09394227846020416),
 (456, 0.06693161223797403),
 (457, 0.025657900289539272),
 (458, 0.0),
 (459, 0.0),
 (460, 0.0),
 (461, 0.033671751485073696),
 (462, 0.038180177416060626),
 (463, 0.03571428571428571),
 (464, 0.0),
 (465, 0.0430730492253948),
 (466, 0.06388765649999399),
 (467, 0.024147264420814756),
 (468, 0.1061116218154582),
 (469, 0.08001600480160055),
 (470, 0.02749286996141075),
 (471, 0.025253813613805264),
 (472, 0.08247860988423225),
 (473, 0.0),
 (474, 0.025657900289539272),
 (475, 0.04829452884162951),
 (476, 0.0893633203101749),
 (477, 0.062347968638854966),
 (478, 0.1020408163265306),
 (479, 0.02449979787750126),
 (480, 0.022875450543583874),
 (481, 0.0),
 (482, 0.025657900289539272),
 (483, 0.062347968638854966),
 (484, 0.030457245193658628),
 (485, 0.062347968638854966),
 (486, 0.07705141285294195),
 (487, 0.06388765649999399),
 (488, 0.02083785592827065),
 (489, 0.07377111135633174),
 (490, 0.06388765649999399),
 (491, 0.04697113923010208),
 (492, 0.0),
 (493, 0.019090088708030313),
 (494, 0.038180177416060626),
 (495, 0.032773676267223106),
 (496, 0.0),
 (497, 0.09137173558097589),
 (498, 0.0),
 (499, 0.0),
 (500, 0.09947294626039876),
 (501, 0.0),
 (502, 0.07045670884515312),
 (503, 0.05957554687344993),
 (504, 0.0),
 (505, 0.060914490387317256),
 (506, 0.031173984319427483),
 (507, 0.02348556961505104),
 (508, 0.07958371636159366),
 (509, 0.02699746235780194),
 (510, 0.10101525445522105),
 (511, 0.08571428571428572),
 (512, 0.09137173558097589),
 (513, 0.07349939363250378),
 (514, 0.0),
 (515, 0.0),
 (516, 0.0),
 (517, 0.02106313659355673),
 (518, 0.05050762722761053),
 (519, 0.056033181468052584),
 (520, 0.0),
 (521, 0.02608202654786505),
 (522, 0.0),
 (523, 0.04899959575500252),
 (524, 0.02749286996141075),
 (525, 0.025657900289539272),
 (526, 0.02608202654786505),
 (527, 0.038180177416060626),
 (528, 0.10101525445522105),
 (529, 0.0915018021743355),
 (530, 0.09832102880166932),
 (531, 0.044086671417740544),
 (532, 0.0),
 (533, 0.0),
 (534, 0.07142857142857142),
 (535, 0.08404977220207888),
 (536, 0.02652790545386455),
 (537, 0.06388765649999399),
 (538, 0.12469593727770993),
 (539, 0.05399492471560388),
 (540, 0.07460470969529907),
 (541, 0.04829452884162951),
 (542, 0.05676567244564473),
 (543, 0.02486823656509969),
 (544, 0.0893633203101749),
 (545, 0.10101525445522105),
 (546, 0.0),
 (547, 0.062347968638854966),
 (548, 0.025253813613805264),
 (549, 0.05050762722761053),
 (550, 0.031943828249996996),
 (551, 0.02178551004751495),
 (552, 0.02857142857142857),
 (553, 0.16198477414681162),
 (554, 0.0),
 (555, 0.0),
 (556, 0.08099238707340582),
 (557, 0.05399492471560388),
 (558, 0.0),
 (559, 0.031173984319427483),
 (560, 0.021295885499998),
 (561, 0.09352195295828244),
 (562, 0.062347968638854966),
 (563, 0.0),
 (564, 0.0893633203101749),
 (565, 0.0),
 (566, 0.0),
 (567, 0.02699746235780194),
 (568, 0.08404977220207888),
 (569, 0.022875450543583874),
 (570, 0.09583148474999098),
 (571, 0.06388765649999399),
 (572, 0.0),
 (573, 0.06251356778481196),
 (574, 0.107682623063487),
 (575, 0.07697370086861782),
 (576, 0.09658905768325902),
 (577, 0.028016590734026292),
 (578, 0.0),
 (579, 0.062347968638854966),
 (580, 0.07142857142857142),
 (581, 0.06554735253444621),
 (582, 0.06862635163075162),
 (583, 0.06776309271789384),
 (584, 0.0),
 (585, 0.029160592175990218),
 (586, 0.07045670884515312),
 (587, 0.06862635163075162),
 (588, 0.08571428571428572),
 (589, 0.09658905768325902),
 (590, 0.1870439059165649),
 (591, 0.0),
 (592, 0.02348556961505104),
 (593, 0.023174488732966077),
 (594, 0.051315800579078544),
 (595, 0.02348556961505104),
 (596, 0.04462107482531602),
 (597, 0.0893633203101749),
 (598, 0.06734350297014739),
 (599, 0.03344032777032302),
 (600, 0.06776309271789384),
 (601, 0.057788559639706465),
 (602, 0.0893633203101749),
 (603, 0.07824607964359515),
 (604, 0.030457245193658628),
 (605, 0.04973647313019938),
 (606, 0.1224989893875063),
 (607, 0.10647942749999),
 (608, 0.060914490387317256),
 (609, 0.07958371636159366),
 (610, 0.020619652471058066),
 (611, 0.11587244366483038),
 (612, 0.04899959575500252),
 (613, 0.09832102880166932),
 (614, 0.051315800579078544),
 (615, 0.12777531299998798),
 (616, 0.0),
 (617, 0.028016590734026292),
 (618, 0.047619047619047616),
 (619, 0.0),
 (620, 0.060914490387317256),
 (621, 0.09583148474999098),
 (622, 0.08425254637422692),
 (623, 0.0),
 (624, 0.032773676267223106),
 (625, 0.0549857399228215),
 (626, 0.02857142857142857),
 (627, 0.06554735253444621),
 (628, 0.04517539514526256),
 (629, 0.10892755023757475),
 (630, 0.02652790545386455),
 (631, 0.0),
 (632, 0.11742784807525519),
 (633, 0.044086671417740544),
 (634, 0.024147264420814756),
 (635, 0.04517539514526256),
 (636, 0.0),
 (637, 0.02449979787750126),
 (638, 0.0),
 (639, 0.0),
 (640, 0.04829452884162951),
 (641, 0.02749286996141075),
 (642, 0.031173984319427483),
 (643, 0.07349939363250378),
 (644, 0.0521640530957301),
 (645, 0.06952346619889824),
 (646, 0.0),
 (647, 0.12828950144769635),
 (648, 0.030457245193658628),
 (649, 0.0),
 (650, 0.028016590734026292),
 (651, 0.02652790545386455),
 (652, 0.10101525445522105),
 (653, 0.038180177416060626),
 (654, 0.1129384878631564),
 (655, 0.051315800579078544),
 (656, 0.02449979787750126),
 (657, 0.054428625857224494),
 (658, 0.09269795493186431),
 (659, 0.06862635163075162),
 (660, 0.08748177652797065),
 (661, 0.0),
 (662, 0.056033181468052584),
 (663, 0.05714285714285714),
 (664, 0.0549857399228215),
 (665, 0.06776309271789384),
 (666, 0.09523809523809523),
 (667, 0.04973647313019938),
 (668, 0.0893633203101749),
 (669, 0.09137173558097589),
 (670, 0.085183541999992),
 (671, 0.04575090108716775),
 (672, 0.10101525445522105),
 (673, 0.0435710200950299),
 (674, 0.07045670884515312),
 (675, 0.0),
 (676, 0.05957554687344993),
 (677, 0.07576144084141578),
 (678, 0.056033181468052584),
 (679, 0.04973647313019938),
 (680, 0.08099238707340582),
 (681, 0.029787773436724965),
 (682, 0.0),
 (683, 0.07460470969529907),
 (684, 0.060914490387317256),
 (685, 0.0692958928675237),
 (686, 0.0),
 (687, 0.029787773436724965),
 (688, 0.0),
 (689, 0.0),
 (690, 0.09947294626039876),
 (691, 0.060914490387317256),
 (692, 0.0),
 (693, 0.060914490387317256),
 (694, 0.1237179148263484),
 (695, 0.1458029608799511),
 (696, 0.107682623063487),
 (697, 0.02749286996141075),
 (698, 0.04123930494211613),
 (699, 0.0),
 (700, 0.058321184351980436),
 (701, 0.0),
 (702, 0.0435710200950299),
 (703, 0.0),
 (704, 0.0),
 (705, 0.0),
 (706, 0.0),
 (707, 0.0),
 (708, 0.04462107482531602),
 (709, 0.02040816326530612),
 (710, 0.021295885499998),
 (711, 0.08404977220207888),
 (712, 0.05050762722761053),
 (713, 0.025253813613805264),
 (714, 0.109971479845643),
 (715, 0.031943828249996996),
 (716, 0.09583148474999098),
 (717, 0.1224989893875063),
 (718, 0.04973647313019938),
 (719, 0.0),
 (720, 0.0530558109077291),
 (721, 0.05957554687344993),
 (722, 0.0),
 (723, 0.04697113923010208),
 (724, 0.1224989893875063),
 (725, 0.0),
 (726, 0.058321184351980436),
 (727, 0.023809523809523808),
 (728, 0.06862635163075162),
 (729, 0.032773676267223106),
 (730, 0.04081632653061224),
 (731, 0.1043281061914602),
 (732, 0.06776309271789384),
 (733, 0.022875450543583874),
 (734, 0.023809523809523808),
 (735, 0.05050762722761053),
 (736, 0.09352195295828244),
 (737, 0.10263160115815709),
 (738, 0.031173984319427483),
 (739, 0.13109470506889243),
 (740, 0.08099238707340582),
 (741, 0.1043281061914602),
 (742, 0.0),
 (743, 0.02348556961505104),
 (744, 0.02857142857142857),
 (745, 0.06734350297014739),
 (746, 0.05050762722761053),
 (747, 0.10647942749999),
 (748, 0.0),
 (749, 0.024147264420814756),
 (750, 0.04517539514526256),
 (751, 0.03464794643376185),
 (752, 0.04829452884162951),
 (753, 0.10101525445522108),
 (754, 0.0),
 (755, 0.107682623063487),
 (756, 0.029160592175990218),
 (757, 0.02857142857142857),

In [67]:
sorted(list(enumerate(similarity[new[new['title'] == 'The Dark Knight Rises'].index[0]])), reverse = True,  key = lambda x:x[1])

[(3, 1.0000000000000007),
 (65, 0.3711537444790452),
 (119, 0.3370101854969078),
 (1363, 0.3276655078039745),
 (1362, 0.3024215695755183),
 (299, 0.29172998299578906),
 (210, 0.2414726442081475),
 (3595, 0.23809523809523808),
 (2390, 0.22131333406899523),
 (4641, 0.21428571428571427),
 (428, 0.2040816326530612),
 (1670, 0.2020305089104422),
 (3077, 0.2020305089104422),
 (1184, 0.19611613513818404),
 (2513, 0.191662969499982),
 (3863, 0.191662969499982),
 (3825, 0.18788455692040834),
 (590, 0.1870439059165649),
 (761, 0.18569533817705186),
 (9, 0.1853959098637286),
 (4412, 0.18442777839082936),
 (3879, 0.18070158058105024),
 (1900, 0.17960530202677488),
 (1494, 0.17872664062034976),
 (3024, 0.17872664062034976),
 (1746, 0.17677669529663687),
 (3720, 0.1722921969015792),
 (4231, 0.1722921969015792),
 (873, 0.17229219690157918),
 (2394, 0.1683587574253685),
 (3336, 0.1683587574253685),
 (1404, 0.16809954440415775),
 (1054, 0.1649572197684645),
 (1149, 0.1649572197684645),
 (1199, 0.1649572197684645),
 (3972, 0.16386838133611553),
 (553, 0.16198477414681162),
 (2160, 0.16198477414681162),
 (3310, 0.16198477414681162),
 (3326, 0.16198477414681162),
 (4148, 0.16198477414681162),
 (1256, 0.16071428571428567),
 (209, 0.15971914124998499),
 (3261, 0.15971914124998499),
 (2014, 0.1591674327231873),
 (370, 0.1564921592871903),
 (4341, 0.1564921592871903),
 (1239, 0.15617376188860607),
 (762, 0.15586992159713742),
 (818, 0.15586992159713742),
 (1866, 0.15586992159713742),
 (2342, 0.15586992159713742),
 (4652, 0.15586992159713742),
 (1046, 0.15394740173723562),
 (408, 0.15228622596829314),
 (1205, 0.1515228816828316),
 (4071, 0.15152288168283157),
 (4173, 0.15152288168283157),
 (116, 0.14920941939059815),
 (1248, 0.14920941939059815),
 (1650, 0.14920941939059815),
 (2246, 0.14920941939059815),
 (2044, 0.1489388671836248),
 (2211, 0.1489388671836248),
 (3264, 0.1489388671836248),
 (3673, 0.1489388671836248),
 (1437, 0.14754222271266348),
 (1476, 0.14754222271266348),
 (3363, 0.14754222271266348),
 (3941, 0.14754222271266348),
 (695, 0.1458029608799511),
 (879, 0.1458029608799511),
 (1249, 0.1458029608799511),
 (4775, 0.1458029608799511),
 (1038, 0.14488358652488853),
 (1733, 0.14488358652488853),
 (41, 0.14285714285714285),
 (238, 0.14285714285714285),
 (377, 0.14285714285714285),
 (866, 0.14285714285714285),
 (1181, 0.14285714285714285),
 (1463, 0.14285714285714285),
 (1544, 0.14285714285714285),
 (2441, 0.14285714285714285),
 (2981, 0.14285714285714285),
 (3303, 0.14285714285714285),
 (2261, 0.14008295367013146),
 (3066, 0.14008295367013146),
 (2297, 0.1385917857350474),
 (3308, 0.1385917857350474),
 (3420, 0.1385917857350474),
 (3840, 0.1385917857350474),
 (369, 0.13746434980705374),
 (2404, 0.13725270326150324),
 (2592, 0.13725270326150324),
 (1087, 0.13552618543578768),
 (283, 0.1349873117890097),
 (405, 0.1349873117890097),
 (978, 0.1349873117890097),
 (1771, 0.1349873117890097),
 (2638, 0.1349873117890097),
 (3801, 0.1349873117890097),
 (808, 0.13468700594029479),
 (1052, 0.13468700594029479),
 (1521, 0.13468700594029479),
 (1734, 0.13468700594029479),
 (2199, 0.13468700594029479),
 (2551, 0.13468700594029479),
 (1352, 0.13386322447594806),
 (807, 0.13263952726932277),
 (968, 0.13263952726932277),
 (1498, 0.13263952726932277),
 (1726, 0.13263952726932277),
 (1418, 0.13226001425322162),
 (739, 0.13109470506889243),
 (1424, 0.13109470506889243),
 (1624, 0.13109470506889243),
 (2259, 0.13109470506889243),
 (4270, 0.13109470506889243),
 (303, 0.13041013273932525),
 (2280, 0.13041013273932525),
 (4105, 0.13041013273932525),
 (774, 0.12921914767618442),
 (1272, 0.12921914767618442),
 (1276, 0.12921914767618442),
 (1879, 0.12921914767618442),
 (647, 0.12828950144769635),
 (1250, 0.12828950144769635),
 (2655, 0.12828950144769635),
 (157, 0.12777531299998798),
 (615, 0.12777531299998798),
 (1090, 0.12777531299998798),
 (2961, 0.12777531299998798),
 (3297, 0.12777531299998798),
 (3421, 0.12777531299998798),
 (3875, 0.12777531299998798),
 (1772, 0.1263788195613404),
 (1086, 0.12626906806902632),
 (1257, 0.12626906806902632),
 (1485, 0.12626906806902632),
 (2728, 0.1250271355696239),
 (2963, 0.1250271355696239),
 (538, 0.12469593727770993),
 (1944, 0.12469593727770993),
 (2508, 0.12469593727770993),
 (2661, 0.12469593727770993),
 (3860, 0.12469593727770993),
 (3946, 0.12469593727770993),
 (4408, 0.12469593727770993),
 (4633, 0.12469593727770993),
 (4667, 0.12469593727770993),
 (82, 0.12434118282549846),
 (1281, 0.12434118282549846),
 (4364, 0.12434118282549846),
 (153, 0.1237179148263484),
 (694, 0.1237179148263484),
 (4330, 0.1237179148263484),
 (3413, 0.12371791482634839),
 (3733, 0.12371791482634839),
 (4261, 0.12371791482634839),
 (170, 0.1224989893875063),
 (212, 0.1224989893875063),
 (606, 0.1224989893875063),
 (717, 0.1224989893875063),
 (724, 0.1224989893875063),
 (1012, 0.1224989893875063),
 (3675, 0.1224989893875063),
 (25, 0.12244897959183672),
 (29, 0.12244897959183672),
 (224, 0.12244897959183672),
 (56, 0.12182898077463451),
 (259, 0.12182898077463451),
 (1092, 0.12182898077463451),
 (2310, 0.12182898077463451),
 (2741, 0.12182898077463451),
 (3839, 0.12182898077463451),
 (3855, 0.12182898077463451),
 (4505, 0.12182898077463451),
 (4683, 0.12182898077463451),
 (3948, 0.12121830534626528),
 (782, 0.12073632210407378),
 (884, 0.12073632210407378),
 (919, 0.12073632210407378),
 (1284, 0.12073632210407378),
 (1470, 0.12073632210407378),
 (1632, 0.12073632210407378),
 (1633, 0.12073632210407378),
 (1952, 0.12073632210407378),
 (3599, 0.12073632210407378),
 (985, 0.12002400720240082),
 (1541, 0.12002400720240082),
 (976, 0.11915109374689986),
 (1085, 0.11915109374689986),
 (1306, 0.11915109374689986),
 (2348, 0.11915109374689986),
 (3549, 0.11915109374689986),
 (3857, 0.11915109374689986),
 (3968, 0.11915109374689986),
 (4357, 0.11915109374689986),
 (4452, 0.11915109374689986),
 (1233, 0.11904761904761904),
 (3791, 0.11904761904761904),
 (2032, 0.11886432776254911),
 (314, 0.1188643277625491),
 (1673, 0.1188643277625491),
 (2675, 0.1188643277625491),
 (3978, 0.1188643277625491),
 (312, 0.11742784807525519),
 (632, 0.11742784807525519),
 (1013, 0.11742784807525519),
 (1455, 0.11742784807525519),
 (2476, 0.11742784807525519),
 (3330, 0.11742784807525519),
 (3347, 0.11742784807525519),
 (122, 0.11664236870396087),
 (160, 0.11664236870396087),
 (920, 0.11664236870396087),
 (977, 0.11664236870396087),
 (1055, 0.11664236870396087),
 (1253, 0.11664236870396087),
 (1669, 0.11664236870396087),
 (2266, 0.11664236870396087),
 (2532, 0.11664236870396087),
 (2564, 0.11664236870396087),
 (2928, 0.11664236870396087),
 (97, 0.11587244366483038),
 (425, 0.11587244366483038),
 (611, 0.11587244366483038),
 (1375, 0.11587244366483038),
 (2213, 0.11587244366483038),
 (3522, 0.11587244366483038),
 (2480, 0.11454053224818188),
 (3130, 0.11454053224818188),
 (3159, 0.11454053224818188),
 (3510, 0.11454053224818188),
 (3728, 0.11454053224818188),
 (3829, 0.11454053224818188),
 (4737, 0.11454053224818188),
 (1061, 0.11437725271791938),
 (1180, 0.11437725271791938),
 (449, 0.11428571428571428),
 (941, 0.11428571428571428),
 (983, 0.11428571428571428),
 (1027, 0.11428571428571428),
 (1341, 0.11428571428571428),
 (1425, 0.11428571428571428),
 (1492, 0.11428571428571428),
 (1961, 0.11428571428571428),
 (4781, 0.11428571428571428),
 (1136, 0.11396057645963793),
 (654, 0.1129384878631564),
 (1559, 0.1129384878631564),
 (1592, 0.1129384878631564),
 (1659, 0.1129384878631564),
 (1992, 0.1129384878631564),
 (2052, 0.1129384878631564),
 (3044, 0.1129384878631564),
 (4133, 0.1129384878631564),
 (1898, 0.1125483710226193),
 (72, 0.11206636293610517),
 (1079, 0.11206636293610517),
 (1834, 0.11206636293610517),
 (1850, 0.11206636293610517),
 (1903, 0.11206636293610517),
 (2066, 0.11206636293610517),
 (2283, 0.11206636293610517),
 (2615, 0.11206636293610517),
 (3037, 0.11206636293610517),
 (3114, 0.11206636293610517),
 (3834, 0.11206636293610517),
 (4491, 0.11206636293610517),
 (777, 0.11155268706329005),
 (950, 0.11155268706329005),
 (1041, 0.11065666703449761),
 (1400, 0.11065666703449761),
 (3177, 0.11065666703449761),
 (4130, 0.11065666703449761),
 (4139, 0.11065666703449761),
 (4463, 0.11065666703449761),
 (248, 0.11021667854435135),
 (1856, 0.11021667854435135),
 (275, 0.109971479845643),
 (714, 0.109971479845643),
 (958, 0.109971479845643),
 (1161, 0.109971479845643),
 (1380, 0.109971479845643),
 (2461, 0.109971479845643),
 (3301, 0.109971479845643),
 (3692, 0.109971479845643),
 (3902, 0.109971479845643),
 (4142, 0.109971479845643),
 (821, 0.1097458970853394),
 (281, 0.10892755023757475),
 (629, 0.10892755023757475),
 (4117, 0.10892755023757475),
 (965, 0.10798984943120776),
 (1278, 0.10798984943120776),
 (1342, 0.10798984943120776),
 (2440, 0.10798984943120776),
 (2559, 0.10798984943120776),
 (3620, 0.10798984943120776),
 (4253, 0.10798984943120776),
 (286, 0.107682623063487),
 (342, 0.107682623063487),
 (574, 0.107682623063487),
 (696, 0.107682623063487),
 (755, 0.107682623063487),
 (834, 0.107682623063487),
 (1462, 0.107682623063487),
 (3734, 0.107682623063487),
 (3908, 0.107682623063487),
 (4077, 0.107682623063487),
 (205, 0.10714285714285714),
 (771, 0.10714285714285714),
 (1033, 0.10714285714285714),
 (1236, 0.10714285714285714),
 (2780, 0.10714285714285714),
 (3243, 0.10714285714285714),
 (3533, 0.10714285714285714),
 (3572, 0.10714285714285714),
 (3627, 0.10714285714285714),
 (4137, 0.10714285714285714),
 (4324, 0.10714285714285714),
 (4783, 0.10714285714285714),
 (215, 0.10647942749999),
 (307, 0.10647942749999),
 (607, 0.10647942749999),
 (747, 0.10647942749999),
 (2286, 0.10647942749999),
 (3545, 0.10647942749999),
 (4449, 0.10647942749999),
 (198, 0.1061116218154582),
 (242, 0.1061116218154582),
 (279, 0.1061116218154582),
 (282, 0.1061116218154582),
 (339, 0.1061116218154582),
 (351, 0.1061116218154582),
 (468, 0.1061116218154582),
 (830, 0.1061116218154582),
 (1196, 0.1061116218154582),
 (1490, 0.1061116218154582),
 (2201, 0.1061116218154582),
 (2552, 0.1061116218154582),
 (2798, 0.1061116218154582),
 (2984, 0.1061116218154582),
 (3320, 0.1061116218154582),
 (3845, 0.1061116218154582),
 (4374, 0.1061116218154582),
 (2153, 0.10531568296778365),
 (3942, 0.10531568296778365),
 (280, 0.1043281061914602),
 (731, 0.1043281061914602),
 (741, 0.1043281061914602),
 (779, 0.1043281061914602),
 (844, 0.1043281061914602),
 (2879, 0.1043281061914602),
 (3322, 0.1043281061914602),
 (3451, 0.1043281061914602),
 (3647, 0.1043281061914602),
 (180, 0.10418927964135324),
 (189, 0.10394383930128556),
 (850, 0.10394383930128556),
 (892, 0.10394383930128556),
 (1078, 0.10394383930128556),
 (1197, 0.10394383930128556),
 (1360, 0.10394383930128556),
 (1721, 0.10394383930128556),
 (2275, 0.10394383930128556),
 (2326, 0.10394383930128556),
 (2590, 0.10394383930128556),
 (2882, 0.10394383930128556),
 (2919, 0.10394383930128556),
 (3288, 0.10394383930128556),
 (3496, 0.10394383930128556),
 (3745, 0.10394383930128556),
 (3837, 0.10394383930128556),
 (1491, 0.10394383930128555),
 (139, 0.10309826235529033),
 (2256, 0.10309826235529033),
 (2549, 0.10309826235529033),
 (3731, 0.10309826235529033),
 (376, 0.10263160115815709),
 (437, 0.10263160115815709),
 (737, 0.10263160115815709),
 (867, 0.10263160115815709),
 (1208, 0.10263160115815709),
 (1388, 0.10263160115815709),
 (1602, 0.10263160115815709),
 (2408, 0.10263160115815709),
 (2409, 0.10263160115815709),
 (2485, 0.10263160115815709),
 (2662, 0.10263160115815709),
 (2799, 0.10263160115815709),
 (3039, 0.10263160115815709),
 (3508, 0.10263160115815709),
 (3541, 0.10263160115815709),
 (3648, 0.10263160115815709),
 (478, 0.1020408163265306),
 (1639, 0.1020408163265306),
 (3078, 0.1020408163265306),
 (2448, 0.1017241421309017),
 (753, 0.10101525445522108),
 (967, 0.10101525445522108),
 (1393, 0.10101525445522108),
 (1438, 0.10101525445522108),
 (1621, 0.10101525445522108),
 (1672, 0.10101525445522108),
 (1680, 0.10101525445522108),
 (1941, 0.10101525445522108),
 (2194, 0.10101525445522108),
 (2222, 0.10101525445522108),
 (2925, 0.10101525445522108),
 (2952, 0.10101525445522108),
 (2987, 0.10101525445522108),
 (3176, 0.10101525445522108),
 (3491, 0.10101525445522108),
 (3590, 0.10101525445522108),
 (3639, 0.10101525445522108),
 (4198, 0.10101525445522108),
 (4258, 0.10101525445522108),
 (4557, 0.10101525445522108),
 (166, 0.10101525445522105),
 (510, 0.10101525445522105),
 (528, 0.10101525445522105),
 (545, 0.10101525445522105),
 (652, 0.10101525445522105),
 (672, 0.10101525445522105),
 (854, 0.10101525445522105),
 (918, 0.10101525445522105),
 (955, 0.10101525445522105),
 (1454, 0.10101525445522105),
 (1598, 0.10101525445522105),
 (1781, 0.10101525445522105),
 (1859, 0.10101525445522105),
 (2591, 0.10101525445522105),
 (2820, 0.10101525445522105),
 (3552, 0.10101525445522105),
 (3607, 0.10101525445522105),
 (4167, 0.10101525445522105),
 (4189, 0.10101525445522105),
 (4435, 0.10101525445522105),
 (939, 0.10002000600200069),
 (1106, 0.10002000600200069),
 (1509, 0.10002000600200069),
 (196, 0.09947294626039876),
 (500, 0.09947294626039876),
 (690, 0.09947294626039876),
 (1108, 0.09947294626039876),
 (1435, 0.09947294626039876),
 (2352, 0.09947294626039876),
 (2446, 0.09947294626039876),
 (2784, 0.09947294626039876),
 (4291, 0.09947294626039876),
 (4453, 0.09947294626039876),
 (2294, 0.09905360646879093),
 (530, 0.09832102880166932),
 (613, 0.09832102880166932),
 (995, 0.09832102880166932),
 (1049, 0.09832102880166932),
 (1154, 0.09832102880166932),
 (1415, 0.09832102880166932),
 (1524, 0.09832102880166932),
 (1645, 0.09832102880166932),
 (1666, 0.09832102880166932),
 (1787, 0.09832102880166932),
 (2136, 0.09832102880166932),
 (2174, 0.09832102880166932),
 (2602, 0.09832102880166932),
 (2837, 0.09832102880166932),
 (2869, 0.09832102880166932),
 (3004, 0.09832102880166932),
 (3213, 0.09832102880166932),
 (3395, 0.09832102880166932),
 (3644, 0.09832102880166932),
 (3982, 0.09832102880166932),
 (4078, 0.09832102880166932),
 (4104, 0.09832102880166932),
 (4164, 0.09832102880166932),
 (4228, 0.09832102880166932),
 (355, 0.09811468853477787),
 (4235, 0.09811468853477787),
 (24, 0.09799919151000504),
 (58, 0.09799919151000504),
 (758, 0.09799919151000504),
 (1146, 0.09799919151000504),
 (1212, 0.09799919151000504),
 (1456, 0.09799919151000504),
 (1531, 0.09799919151000504),
 (1560, 0.09799919151000504),
 (1958, 0.09799919151000504),
 (2209, 0.09799919151000504),
 (2612, 0.09799919151000504),
 (3192, 0.09799919151000504),
 (3557, 0.09799919151000504),
 (36, 0.09658905768325902),
 (576, 0.09658905768325902),
 (589, 0.09658905768325902),
 (988, 0.09658905768325902),
 (1003, 0.09658905768325902),
 (1204, 0.09658905768325902),
 (1764, 0.09658905768325902),
 (1823, 0.09658905768325902),
 (1874, 0.09658905768325902),
 (3108, 0.09658905768325902),
 (4073, 0.09658905768325902),
 (4230, 0.09658905768325902),
 (244, 0.09583148474999098),
 (308, 0.09583148474999098),
 (570, 0.09583148474999098),
 (621, 0.09583148474999098),
 (716, 0.09583148474999098),
 (970, 0.09583148474999098),
 (991, 0.09583148474999098),
 (1443, 0.09583148474999098),
 (1833, 0.09583148474999098),
 (2218, 0.09583148474999098),
 (2228, 0.09583148474999098),
 (2271, 0.09583148474999098),
 (2652, 0.09583148474999098),
 (2779, 0.09583148474999098),
 (3376, 0.09583148474999098),
 (3398, 0.09583148474999098),
 (3767, 0.09583148474999098),
 (4135, 0.09583148474999098),
 (4659, 0.09583148474999098),
 (26, 0.09523809523809523),
 (204, 0.09523809523809523),
 (316, 0.09523809523809523),
 (666, 0.09523809523809523),
 (932, 0.09523809523809523),
 (1025, 0.09523809523809523),
 (1322, 0.09523809523809523),
 (1705, 0.09523809523809523),
 (2224, 0.09523809523809523),
 (2667, 0.09523809523809523),
 (2889, 0.09523809523809523),
 (3296, 0.09523809523809523),
 (3583, 0.09523809523809523),
 (4276, 0.09523809523809523),
 (415, 0.09460945407607455),
 (93, 0.09394227846020416),
 (217, 0.09394227846020416),
 (447, 0.09394227846020416),
 (455, 0.09394227846020416),
 (870, 0.09394227846020416),
 (1122, 0.09394227846020416),
 (1367, 0.09394227846020416),
 (2324, 0.09394227846020416),
 (2418, 0.09394227846020416),
 (2642, 0.09394227846020416),
 (304, 0.09379030918551609),
 (267, 0.09352195295828244),
 (561, 0.09352195295828244),
 (736, 0.09352195295828244),
 (1044, 0.09352195295828244),
 (1156, 0.09352195295828244),
 (1660, 0.09352195295828244),
 (1681, 0.09352195295828244),
 (2355, 0.09352195295828244),
 (2384, 0.09352195295828244),
 (2496, 0.09352195295828244),
 (2579, 0.09352195295828244),
 (2584, 0.09352195295828244),
 (2589, 0.09352195295828244),
 (2651, 0.09352195295828244),
 (2697, 0.09352195295828244),
 (3144, 0.09352195295828244),
 (3224, 0.09352195295828244),
 (3352, 0.09352195295828244),
 (3490, 0.09352195295828244),
 (3886, 0.09352195295828244),
 (3926, 0.09352195295828244),
 (4027, 0.09352195295828244),
 (4145, 0.09352195295828244),
 (4150, 0.09352195295828244),
 (4166, 0.09352195295828244),
 (4257, 0.09352195295828244),
 (4490, 0.09352195295828244),
 (108, 0.09269795493186431),
 (442, 0.09269795493186431),
 (658, 0.09269795493186431),
 (813, 0.09269795493186431),
 (994, 0.09269795493186431),
 (1496, 0.09269795493186431),
 (1930, 0.09269795493186431),
 (2245, 0.09269795493186431),
 (2527, 0.09269795493186431),
 (2575, 0.09269795493186431),
 (2965, 0.09269795493186431),
 (3056, 0.09269795493186431),
 (3184, 0.09269795493186431),
 (163, 0.0915018021743355),
 (182, 0.0915018021743355),
 (354, 0.0915018021743355),
 (529, 0.0915018021743355),
 (767, 0.0915018021743355),
 (788, 0.0915018021743355),
 (1164, 0.0915018021743355),
 (1268, 0.0915018021743355),
 (3298, 0.0915018021743355),
 (3382, 0.0915018021743355),
 (3643, 0.0915018021743355),
 (4751, 0.0915018021743355),
 (85, 0.09145491423778283),
 (236, 0.09137173558097589),
 (497, 0.09137173558097589),
 (512, 0.09137173558097589),
 (669, 0.09137173558097589),
 (826, 0.09137173558097589),
 (894, 0.09137173558097589),
 (1039, 0.09137173558097589),
 (1147, 0.09137173558097589),
 (1152, 0.09137173558097589),
 (1513, 0.09137173558097589),
 (2004, 0.09137173558097589),
 (2100, 0.09137173558097589),
 (2628, 0.09137173558097589),
 (2644, 0.09137173558097589),
 (2887, 0.09137173558097589),
 (2936, 0.09137173558097589),
 (3116, 0.09137173558097589),
 (3238, 0.09137173558097589),
 (3246, 0.09137173558097589),
 (3511, 0.09137173558097589),
 (4479, 0.09137173558097589),
 (4509, 0.09137173558097589),
 (4624, 0.09137173558097589),
 (4733, 0.09137173558097589),
 (357, 0.09035079029052512),
 (1121, 0.09035079029052512),
 (1405, 0.09035079029052512),
 (1433, 0.09035079029052512),
 (1638, 0.09035079029052512),
 (1748, 0.09035079029052512),
 (2007, 0.09035079029052512),
 (2150, 0.09035079029052512),
 (2474, 0.09035079029052512),
 (3128, 0.09035079029052512),
 (3153, 0.09035079029052512),
 (3229, 0.09035079029052512),
 (3313, 0.09035079029052512),
 (3441, 0.09035079029052512),
 (4120, 0.09035079029052512),
 (4353, 0.09035079029052512),
 (2386, 0.08999154119267314),
 (28, 0.0893633203101749),
 (31, 0.0893633203101749),
 (50, 0.0893633203101749),
 (476, 0.0893633203101749),
 (544, 0.0893633203101749),
 (564, 0.0893633203101749),
 (597, 0.0893633203101749),
 (602, 0.0893633203101749),
 (668, 0.0893633203101749),
 (823, 0.0893633203101749),
 (840, 0.0893633203101749),
 (876, 0.0893633203101749),
 (1004, 0.0893633203101749),
 (1076, 0.0893633203101749),
 (1234, 0.0893633203101749),
 (1242, 0.0893633203101749),
 (1423, 0.0893633203101749),
 (1594, 0.0893633203101749),
 (1936, 0.0893633203101749),
 (2117, 0.0893633203101749),
 (3092, 0.0893633203101749),
 (3170, 0.0893633203101749),
 (3211, 0.0893633203101749),
 (3356, 0.0893633203101749),
 (3611, 0.0893633203101749),
 (3933, 0.0893633203101749),
 (4141, 0.0893633203101749),
 (4144, 0.0893633203101749),
 (4399, 0.0893633203101749),
 (4770, 0.0893633203101749),
 (246, 0.08924214965063204),
 (982, 0.08924214965063204),
 (1203, 0.08924214965063204),
 (1457, 0.08924214965063204),
 (1755, 0.08924214965063204),

In [68]:
def recomand(movie):
    index = new[new['title'] == movie].index[0]
    distances = sorted(list(enumerate(similarity[index])), reverse = True, key = lambda x:x[1])
    for i in distances[1:6]:
        print(new.iloc[i[0]].title)

In [69]:
recomand('The Dark Knight Rises')

The Dark Knight
Batman Begins
Batman
Batman
Batman Forever

In [94]:
import numpy as np

In [95]:
random_array = np.random.rand(1,4806)

In [96]:
random_array

array([[0.05066194, 0.80743702, 0.88371075, ..., 0.77416067, 0.42120192,
        0.33487056]])

In [97]:
data_series = pd.Series(random_array[0])
data_series

0       0.050662
1       0.807437
2       0.883711
3       0.851303
4       0.335735
          ...
4801    0.355325
4802    0.732091
4803    0.774161
4804    0.421202
4805    0.334871
Length: 4806, dtype: float64

In [98]:
sorted_series_desc = data_series.sort_values(ascending=False)
sorted_series_desc

3869    0.999989
3933    0.999743
3103    0.998899
4288    0.998864
2833    0.998860
          ...
3491    0.000931
3823    0.000647
528     0.000643
2136    0.000383
366     0.000148
Length: 4806, dtype: float64

In [100]:
sorted_series_desc.head(5).index

Index([3869, 3933, 3103, 4288, 2833], dtype='int64')

In [101]:
new.iloc[sorted_series_desc.head(5).index]

,title,movie_id,tags
3870,August,86549,"August tells the story of two former lovers, T..."
3934,Please Give,40247,"In New York City, a husband and wife butt head..."
3104,Shaolin Soccer,11770,A young Shaolin follower reunites with his dis...
4290,C.H.U.D.,23730,A rash of bizarre murders in New York City see...
2834,Project X,57214,Three high school seniors throw a party to mak...

In [102]:
new.iloc[sorted_series_desc.head(5).index]["title"]

3870            August
3934       Please Give
3104    Shaolin Soccer
4290          C.H.U.D.
2834         Project X
Name: title, dtype: object

In [103]:
list(new.iloc[sorted_series_desc.head(5).index]["title"])

['August', 'Please Give', 'Shaolin Soccer', 'C.H.U.D.', 'Project X']